version: '3.8'
services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=scania_db
    ports:
      - '5431:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
