export enum ErrorCodes {
    ERR_EMAIL_PASSWORD_REQUIRED = "ERR_EMAIL_PASSWORD_REQUIRED",
    ERR_INVALID_CREDENTIALS = "ERR_INVALID_CREDENTIALS",
    ERR_UNEXPECTED_ERROR = "ERR_UNEXPECTED_ERROR",
    ERR_NO_FILE_UPLOAD = "ERR_NO_FILE_UPLOAD",
    ERR_ALREADY_EXISTS = "ERR_ALREADY_EXISTS",
    ERR_INVALID_TOKEN = "ERR_INVALID_TOKEN",
    ERR_TOKEN_EXPIRED = "ERR_TOKEN_EXPIRED",
    ERR_PASSWORD_INVALID = "ERR_PASSWORD_INVALID",
    ERR_PASSWORD_REQUIRED = "ERR_PASSWORD_REQUIRED",
    ERR_USER_NOT_FOUND = "ERR_USER_NOT_FOUND",
    ERR_EMAIL_SEND_FAILED = "ERR_EMAIL_SEND_FAILED",
    ERR_PENDING_INVITATION = "ERR_PENDING_INVITATION"
}
