export enum ErrorCodes {
    ERR_EMAIL_PASSWORD_REQUIRED = "ERR_EMAIL_PASSWORD_REQUIRED",
    ERR_INVALID_CREDENTIALS = "ERR_INVALID_CREDENTIALS",
    ERR_UNEXPECTED_ERROR = "ERR_UNEXPECTED_ERROR",
}
