export type ErrorCodes =
  | 'ERR_EMAIL_PASSWORD_REQUIRED'
  | 'ERR_INVALID_CREDENTIALS'
  | 'ERR_UNEXPECTED_ERROR'
  | 'ERR_INVALID_FILE_STRUCTURE'
  | 'ERR_MISSING_ATTRIBUTES'
  | 'ERR_XML_PARSE_ERROR'
